### ISSUE TITLE
[Epic] Call for papers

### ISSUE THREAD

**Issue by tricoder42** [pyvec/cz.pycon.org-2016#12]
⚠️ **This is tracking issue for all tasks required for publishing Call for papers**
## Content
- [x] Form - Questions/fields on CfP form #17 
- [x] Article - Announcement, mention we aim for high diversity of topics and speakers, which topics we prefer, important dates and what speakers get covered #18 
## App
- [x] CfP form - allow multiple CfP per conference (Talks/Workshops and Financial aid)
- [ ] Scoring system - allow two rounds (anonymous, final)
